#!/bin/env python3
# Client for the resource monitor daemon
import argparse
from sys import stderr

import requests


def do_status(args):
    response: requests.Response = requests.post('http://127.0.0.1:8081/status')

    print("{:>7}\t{:>7}\t{:>7}\t{:>7}\t{:>7}\t{}".format("ID", "CPU%", "MEM%", "CPU%LIM", "MEM%LIM", "COMMAND"))
    for child in response.json()['children']:
        print("{id:6d}\t{cpu:7.1f}\t{memory:7.1f}\t{cpu_limit:7.1f}\t{memory_limit:7.1f}\t{command}".format(
            id=int(child['id']),
            cpu=float(child['resources']['cpu']),
            memory=float(child['resources']['memory']),
            cpu_limit=float(child['limits']['cpu']),
            memory_limit=float(child['limits']['memory']),
            command=child['command'],
        ))


def do_spawn(args):
    response: requests.Response = requests.post(
        'http://127.0.0.1:8081/spawn',
        json={'command': args.command},
    )
    if response.status_code != 200:
        print('ERROR', response.json()['msg'])
        return
    print(response.json()['id'])


def do_terminate(args):
    response: requests.Response = requests.post(
        'http://127.0.0.1:8081/terminate',
        json={'id': args.id},
    )
    if response.status_code != 200:
        print('ERROR', response.json()['msg'])
        return
    print("OK")


def do_limits(args):
    response: requests.Response = requests.post(
        'http://127.0.0.1:8081/limits',
        json={'id': args.id, 'limits': {'cpu': args.cpu, 'memory': args.memory}},
    )
    if response.status_code != 200:
        print('ERROR', response.json()['msg'])
        return
    print("OK")


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers()

    parser_status = subparsers.add_parser('status')
    parser_status.set_defaults(func=do_status)

    parser_spawn = subparsers.add_parser('spawn')
    parser_spawn.add_argument('command')
    parser_spawn.set_defaults(func=do_spawn)

    parser_terminate = subparsers.add_parser('terminate')
    parser_terminate.add_argument('id')
    parser_terminate.set_defaults(func=do_terminate)

    parser_limits = subparsers.add_parser('limits')
    parser_limits.add_argument('id')
    parser_limits.add_argument('--cpu', '-c')
    parser_limits.add_argument('--memory', '-m')
    parser_limits.set_defaults(func=do_limits)

    args = parser.parse_args()
    try:
        args.func(args)
    # except AttributeError:
    #     parser.print_help()
    except requests.exceptions.ConnectionError:
        print("Could not connect to the daemon. Is it running?", file=stderr)
